#cloud-config
packages:
   - apache2
runcmd:
   - echo "$(hostname)" > /var/www/html/index.html
   - systemctl restart apache2

#    #cloud-config
# packages:
#    - nginx
# runcmd:
#    - echo "$(hostname)" > /var/www/html/index.nginx-debian.html
#    - systemctl restart nginx